- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOPS with AWS"
    DURATION: "120HRS"
    TRINER: "Ganesh"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learninng {{COURSE}}, Duration is: {{DURATION}}, Trinaer: {{TRINER}}"