- name: variables to print
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learninng {{COURSE}}, Duration is: {{DURATION}}, Trinaer: {{TRINER}}"