
- name: create ec2 and r53 recors
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-041a4a9b2ebc120c1
    sg_id: "sg-0bdc6d5500f2d30d5"
    ami_id: "ami-0220d79f3f480ecf5"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg-id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances}}"
    regidter: ec2_instance